general:
    worker:
        gpus_per_job: 1

pipeline: [random1, mutate1, full1]

random1:
    pipe_step:
        type: NasPipeStep

    dataset:
        type: Cityscapes
        common:
            root_dir: /cache/datasets/VOC2012
        train:
            list_file: train.txt
            batch_size: 16
            num_workers: 4
            shuffle: true
            Rescale:
                size: 512
            RandomMirror: true
            RandomColor:
                color_factor: [0.95, 1.05]
                contrast_factor: [0.95, 1.05]
                brightness_factor: [0.95, 1.05]
            RandomGaussianBlur:
                kernel_size: 3
            RandomRotation:
                rotation_factor: [-10, 10]
                border_value: [0.485, 0.456, 0.406]
                fill_label: 255
            Normalization:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
        test:
            list_file: val.txt
            Rescale:
                size: 512
            Normalization:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]

    search_space:
        type: SearchSpace
        modules: ['custom']
        custom:
            name: AdelaideFastNAS
            backbone_load_path: /cache/models/mobilenet_v2-b0353104.pth
            backbone_out_sizes: [24, 32, 96, 320]
            op_names: [conv1x1, conv3x3, sep_conv_3x3, sep_conv_5x5, conv3x3_dil3, sep_conv_3x3_dil3, sep_conv_5x5_dil6]
            agg_size: 64
            aux_cell: false
            sep_repeats: 1
            agg_concat: true
            num_classes: 21

    search_algorithm:
        type: AdelaideRandom
        codec: AdelaideCodec
        max_sample: 100

    trainer:
        type: Trainer
        callbacks: AdelaideEATrainerCallback
        codec: AdelaideCodec
        seed: 0
        epochs: 25
        print_step: 50
        optim:
            type: Adam
            lr: !!float 5e-5
        lr_scheduler:
            type: StepLR
            step_size: 5
            gamma: 0.5
        loss:
            type: CrossEntropyLoss
            ignore_index: 255
        metric:
            type: IoUMetric
            num_class: 21

mutate1:
    pipe_step:
        type: NasPipeStep

    dataset:
        ref: random1.dataset

    search_space:
            ref: random1.search_space

    search_algorithm:
        type: AdelaideMutate
        codec: AdelaideCodec
        max_sample: 100
        pareto_front_file: "{local_base_path}/output/random1/pareto_front.csv"
        random_file: "{local_base_path}/output/random1/random.csv"

    trainer:
        ref: random1.trainer
        callbacks: AdelaideEATrainerCallback
        codec: AdelaideCodec
        save_model_desc: True

full1:
    pipe_step:
        type: FullyTrainPipeStep
        models_folder: "{local_base_path}/output/mutate1/"

    dataset:
        ref: random1.dataset
        train:
            batch_size: 24
    
    search_space:
        ref: random1.search_space
        custom:
            sep_repeats: 2

    trainer:
        ref: random1.trainer
        callbacks: AdelaideEATrainerCallback
        codec: AdelaideCodec
        model_statistics: True
        pareto_front_file: "{local_base_path}/output/mutate1/pareto_front.csv"
        random_file: "{local_base_path}/output/random1/random.csv"
        epochs: 100
