general:
    worker:
        gpus_per_job: 1

pipeline: [jdd_search,full_train]

jdd_search:
    pipe_step:
        type: NasPipeStep

    dataset:
        type: JDDData
        train:
            num_workers: 1
            batch_size: 16
            shuffle: true
            pin_memory: True
            distributed: False
        test:
            batch_size: 1
            num_workers: 1
            shuffle: true
            pin_memory: True
            distributed: False

    search_space:
        type: SearchSpace
        modules: ['jddbody']
        jddbody:
            name: JDDNet
            channel_types: ['16', '32', '48']
            channel_prob: [1, 0.5, 0.2]
            block_types: ['R']
            block_prob: [1]
            basic_channel: 16

    search_algorithm:
        type: JDDSearch
        codec: JDDCodec
        generation_num: 20
        individual_num: 8
        elitism_num: 4
        node_num: 16
        min_active: 6
        min_res_start: 1
        min_res_end: 1
        min_flops: 0
        max_flops: 160000000000
        max_resolutions: 5
        mutation_rate: 0.05
        metric_x: flops
        metric_y: params
        metric_z: PSNR

    trainer:
        type: JDDTrainer
        epochs: 10
        stat_epoch: 2
        optim:
            type: Adam
            lr: 0.0001
        lr_scheduler:
            type: MultiStepLR
            milestones: [100,200]
            gamma: 0.5
        loss:
            type: L1Loss
        metric:
            type: compute_sr_metric
            metric_type: psnr
        cuda: True
        seed: 10
        
full_train:
    pipe_step:
        type: FullyTrainPipeStep

    dataset:
        type: JDDData
        train:
            num_workers: 1
            batch_size: 16
            shuffle: true
            pin_memory: True
            distributed: False
        test:
            batch_size: 1
            num_workers: 1
            shuffle: true
            pin_memory: True
            distributed: False

    search_space:
        type: SearchSpace
        modules: ['jddbody']
        jddbody:
            name: JDDNet
            channel_types: ['16', '32', '48']
            channel_prob: [1, 0.5, 0.2]
            block_types: ['R']
            block_prob: [1]
            basic_channel: 16

    trainer:
        type: JDDTrainer
        codec: JDDCodec
        node_num: 16
        min_res_start: 1
        min_res_end: 1
        max_resolutions: 5
        epochs: 500
        stat_epoch: 2
        optim:
            type: Adam
            lr: 0.0001
        lr_scheduler:
            type: MultiStepLR
            milestones: [300,400]
            gamma: 0.5
        loss:
            type: L1Loss
        metric:
            type: compute_sr_metric
            metric_type: psnr
        cuda: True
        seed: 10