general:
    worker:
        timeout: 1000.0
        gpus_per_job: 1
    backend: tensorflow

pipeline: [nas]

nas:
    pipe_step:
        type: NasPipeStep
    search_algorithm:
        type: SimpleRand
        count: 0
        max_num: 50
    search_space:
        type: SearchSpace
        modules: [backbone]
        backbone:
            name: SimpleCnn
            num_class: 10
            fp16: False
            blocks: [1, 2, 3, 4]
            channels: [32, 48, 56, 64]
    trainer:
        type: Trainer
        optim:
            type: MomentumOptimizer
            learning_rate: 0.01
            momentum: 0.9
        lr_scheduler:
            type: CosineAnnealingLR
            T_max: 350.0
        loss:
            type: sparse_softmax_cross_entropy
        metric:
            type: accuracy
        model_desc:
            modules: [backbone]
            backbone:
                name: SimpleCnn
                num_class: 10
                fp16: False
        epochs: 3
        save_steps: 250
        horovod: False
        num_class: 10
    dataset:
        type: Cifar10TF
        data_dir: /cache/datasets/cifar-10-batches-bin
        batch_size: 64
        num_parallel_batches: 64
        fp16: False
